# Generated by Django 2.2.16 on 2020-09-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
    ]
